# Generated by Django 5.2.5 on 2025-09-19 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sales.client'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='category',
            field=models.CharField(choices=[('Hardware', 'Hardware'), ('Lamination & Highlighter', 'Lamination & Highlighter'), ('Veneer', 'Veneer'), ('Sofa_durtains', 'Sofa & Curtains'), ('Modular', 'Modular')], max_length=50),
        ),
    ]
