# Generated by Django 5.2.7 on 2025-10-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_alter_sale_client_alter_saleitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='attend_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
